package Core.Enums;

public enum InterpreterKeyword
{
    INVALID, PERSON, SOCIETY, ECONOMY, COMPANY, MARKET,
    HELP, TEST, EXIT, CALCULATE, POPULATE, HIRE, GOVERNMENT, ADD, PRINT, RANDOM, CASH, PAY, PRODUCE, INCOME, EDUCATION, BUY, SET, BUDGET, CONSUME,
    FOOD
}
